services:
  auth-service:
    build:
      context: ./Services/Auth.Service
    container_name: auth-service
    ports:
      - "5003:8080"
    depends_on:
      - pg-database
  product-service:
    build:
      context: ./Services/Product.Service
    container_name: product-service
    ports:
      - "5001:8080"
    depends_on:
      - pg-database
      
  order-service:
    build:
      context: ./Services/Order.Service
    container_name: order-service
    ports:
      - "5002:8080"
    depends_on:
      - pg-database
      
  pg-database:
    image: postgres:16
    container_name: pg-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    volumes:
      - pg-db-data:/var/lib/postgresql/data
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      
volumes:
  pg-db-data:
